spring:
  application:
    name: Auth-Service
  config:
    import: optional:configserver:http://localhost:2222  
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: haritha123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

auth-service:
  messages: 
    userReg: User Created
    userRegErr: User Creation Failed
    login: Login Success
    loginErr: Invalid Credentials
