
spring:
  application:
    name: 08-Reports-Service
  config:
    import: optional:configserver:http://localhost:2222
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: haritha123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
  jpa:
    hibernate:
      ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8085

# Application Messages Goes Here
reports-service:
 messages:
  orderFetch: All Orders fetched successfully
  orderFetchErr: Failed to fetch all Orders
