
spring:
  application:
    name: 09-Payment-Service
  config:
    import: optional:configserver:http://localhost:2222
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: haritha123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
  jpa:
    hibernate:
      ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1111/
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8086

# Application Messages Goes Here
payment-service:
  keys:
    razorPayAPIKey: xxxxxxxxxxxxxxxx
    razorPaySecretKey: xxxxxxxxxxxxxx
